name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: realsense_ros

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [kinetic, melodic]

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
            docker build . --file Dockerfile --tag $IMAGE_NAME:${{matrix.ros_distro}} --build-arg ros_distro=${{matrix.ros_distro}}